### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by burcuerdogann** [HATE-Company/OfficialWebsite-v1.0-web2.0#7]
- [x] Change title: "HATE Company"
- [x] Create images/assets folder. Ask logo in SVG format.
- [x] legal and w classes' font-family is Courier New.
Not: HATE Company için kullandığımız tek font ailesi Courier New'dir.
- [x] Create ReadMe file.
Not: Örnekler incelenerek -alışkanlık kazanılması adına- web sitesi için basic bir readme file oluşturulabilir.
